In [1]:
from ctra_kalman_filter import CTRAKalmanFilter
import numpy as np

kf = CTRAKalmanFilter()
measurement = np.array([100, 50, 1.57])  # Example: [x, y, theta]
mean, cov = kf.initiate(measurement)
print("Initial State:", mean)
print("Initial Covariance:", cov)


Initial State: [100.    50.     0.     1.57   0.     0.  ]
Initial Covariance: [[0.01 0.   0.   0.   0.   0.  ]
 [0.   0.01 0.   0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.   0.01 0.  ]
 [0.   0.   0.   0.   0.   0.01]]


In [2]:
dt = 1.0
mean, cov = kf.predict(mean, cov, dt)
print("Predicted State:", mean)
print("Predicted Covariance:", cov)


Predicted State: [100.    50.     0.     1.57   0.     0.  ]
Predicted Covariance: [[0.06 0.   0.   0.   0.   0.  ]
 [0.   0.06 0.   0.   0.   0.  ]
 [0.   0.   1.05 0.   0.   0.  ]
 [0.   0.   0.   0.3  0.   0.  ]
 [0.   0.   0.   0.   0.06 0.  ]
 [0.   0.   0.   0.   0.   0.06]]


In [9]:
from matching import fuse_motion_ctra

tracks = [...]  # Populate with mock track states
detections = [...]  # Populate with mock detection states
cost_matrix = np.zeros((len(tracks), len(detections)))  # Mock IoU costs
fused_cost = fuse_motion_ctra(kf, cost_matrix, tracks, detections)
print("Fused Cost Matrix:", fused_cost)


AttributeError: 'CTRAKalmanFilter' object has no attribute 'predict_state'

In [24]:
# Import necessary modules
import numpy as np
from ctra_kalman_filter import CTRAKalmanFilter

# Initialize the Kalman filter
kf = CTRAKalmanFilter()

# Test 1: Initialization
print("==== TEST 1: Initialization ====")
initial_measurement = np.array([100.0, 50.0, 1.57])  # [x, y, θ]
mean, covariance = kf.initiate(initial_measurement)
print("Initial State shape:", mean.shape)

print("Initialized Mean:")
print(mean)
print(mean.shape)
print("Initialized Covariance:")
print(covariance)
print(covariance.shape)

# Expected Output:
# mean = [100.0, 50.0, 0.0, 1.57, 0.0, 0.0]
# covariance = diagonal matrix with defined std squared

# Test 2: Prediction
print("\n==== TEST 2: Prediction ====")
predicted_mean, predicted_covariance = kf.predict(mean, covariance, dt=2.0)

print("Predicted Mean:")
print(predicted_mean)
print(predicted_mean.shape)
print("Predicted Covariance:")
print(predicted_covariance)
print(predicted_covariance.shape)

# Test 3: Update
measurement = np.array([102.0, 52.0])  # Pad with zeros
print('measurement shape:', measurement.shape)
updated_mean, updated_covariance = kf.update(predicted_mean, predicted_covariance, measurement)
print("Updated Mean:", updated_mean)
print("Updated Covariance:", updated_covariance)

# Test 4: Predict State (Alternative Method)
print("\n==== TEST 4: Predict State ====")
predicted_state = kf.predict_state(mean, dt=1.0)

print("Predicted State:")
print(predicted_state)

# Test 5: Multi Predict
print("\n==== TEST 5: Multi Predict ====")
means = np.array([[100.0, 50.0, 1.0, 1.57, 0.1, 0.01],
                  [200.0, 150.0, 2.0, 0.0, 0.2, 0.02]])
covariances = np.array([np.eye(6), np.eye(6)])
multi_predicted_means, multi_predicted_covariances = kf.multi_predict(means, covariances, dt=1.0)

print("Multi Predicted Means:")
print(multi_predicted_means)
print("Multi Predicted Covariances:")
print(multi_predicted_covariances)


==== TEST 1: Initialization ====
Initial State shape: (6,)
Initialized Mean:
[100.    50.     0.     1.57   0.     0.  ]
(6,)
Initialized Covariance:
[[0.01 0.   0.   0.   0.   0.  ]
 [0.   0.01 0.   0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.   0.01 0.  ]
 [0.   0.   0.   0.   0.   0.01]]
(6, 6)

==== TEST 2: Prediction ====
Predicted Mean:
[100.    50.     0.     1.57   0.     0.  ]
(6,)
Predicted Covariance:
[[0.06 0.   0.   0.   0.   0.  ]
 [0.   0.06 0.   0.   0.   0.  ]
 [0.   0.   1.05 0.   0.   0.  ]
 [0.   0.   0.   0.3  0.   0.  ]
 [0.   0.   0.   0.   0.06 0.  ]
 [0.   0.   0.   0.   0.   0.06]]
(6, 6)
measurement shape: (2,)


ValueError: operands could not be broadcast together with shapes (2,) (4,) 